version: '3.8'
services:
  auth-service:
    environment:
      - NODE_ENV=dev
    volumes:
      - ./services/auth-service:/app
      - /app/node_modules

  product-service:
    environment:
      - NODE_ENV=dev
    volumes:
      - ./services/product-service:/app
      - /app/node_modules

  order-service:
    environment:
      - NODE_ENV=dev
    volumes:
      - ./services/order-service:/app
      - /app/node_modules

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"