server {
    listen 8080;
    server_name localhost;

    # Gestion du Frontend
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Redirection Auth - Note le "/" après "auth" et après "3001"
    location /api/auth/ {
        proxy_pass http://auth-service:3001/api/auth/; 
    }

    # Redirection Product
    location /api/product/ {
        proxy_pass http://product-service:3000/api/product/;
    }

    # Redirection Order
    location /api/order/ {
        proxy_pass http://order-service:3002/api/order/;
    }
}