server {
    listen 8080;
    server_name localhost;

    # Gestion du Frontend (fichiers statiques)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Redirection vers le Microservice Auth
    location /api/auth/ {
        proxy_pass http://auth-service:3001/; 
    }

    # Redirection vers le Microservice Product
    location /api/product/ {
        proxy_pass http://product-service:3000/;
    }

    # Redirection vers le Microservice Order
    location /api/order/ {
        proxy_pass http://order-service:3002/;
    }
}