server {
    listen 80;
    server_name localhost;

    # Gestion du Frontend
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api/auth/ {
        proxy_pass http://auth-service:3001/api/auth/; 
    }

    # Redirection Product
    location /api/products/ {
        proxy_pass http://product-service:3000/api/products/;
    }

    location /api/cart/ {
        proxy_pass http://product-service:3000/api/cart/; 
    }

    # Redirection Order
    location /api/orders/ {
        proxy_pass http://order-service:3002/api/orders/;
    }
}