services:
  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/auth-service:/app
      - /app/node_modules
    networks:
      - ecom-network

  product-service:
    build:
      context: ./services/product-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/product-service:/app
      - /app/node_modules
    ports:
      - "3000:3000"  
    networks:
      - ecom-network

  order-service:
    build:
      context: ./services/order-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/order-service:/app
      - /app/node_modules
    networks:
      - ecom-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - ecom-network

networks:
  ecom-network:
    external: false